MEETING_STATUS_UPLOADED = "uploaded"
MEETING_STATUS_PROCESSING = "processing"
MEETING_STATUS_TRANSCRIBED = "transcribed"
MEETING_STATUS_SUMMARIZING = "summarizing"
MEETING_STATUS_COMPLETED = "completed"
MEETING_STATUS_FAILED = "failed"


ALLOWED_STATUS_TRANSITIONS = {
    MEETING_STATUS_UPLOADED: {
        MEETING_STATUS_PROCESSING,
        MEETING_STATUS_FAILED,
    },
    MEETING_STATUS_PROCESSING: {
        MEETING_STATUS_TRANSCRIBED,
        MEETING_STATUS_FAILED,
    },
    MEETING_STATUS_TRANSCRIBED: {
        MEETING_STATUS_SUMMARIZING,
        MEETING_STATUS_FAILED,
    },
    MEETING_STATUS_SUMMARIZING: {
        MEETING_STATUS_COMPLETED,
        MEETING_STATUS_FAILED,
    },
    MEETING_STATUS_COMPLETED: set(),
    MEETING_STATUS_FAILED: set(),
}